// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtcOOdz50VmuwjRsWJx9XyBYDo-5Y-Z18',
    appId: '1:192377407511:web:d498d17ced3a3e7547f452',
    messagingSenderId: '192377407511',
    projectId: 'civiclens-d5da2',
    authDomain: 'civiclens-d5da2.firebaseapp.com',
    storageBucket: 'civiclens-d5da2.firebasestorage.app',
    measurementId: 'G-CH0NT3ZWK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgx_P4-Kn0_4rULcWyLvNUIdUkQ-DzMaA',
    appId: '1:192377407511:android:91ae7d8e2e2f2e7047f452',
    messagingSenderId: '192377407511',
    projectId: 'civiclens-d5da2',
    storageBucket: 'civiclens-d5da2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxapZ6V8ELEk4g9dJ7F_0hDcYfXcWqoo4',
    appId: '1:192377407511:ios:ab58e1c7e7b4b3dc47f452',
    messagingSenderId: '192377407511',
    projectId: 'civiclens-d5da2',
    storageBucket: 'civiclens-d5da2.firebasestorage.app',
    iosBundleId: 'com.example.civiclens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxapZ6V8ELEk4g9dJ7F_0hDcYfXcWqoo4',
    appId: '1:192377407511:ios:ab58e1c7e7b4b3dc47f452',
    messagingSenderId: '192377407511',
    projectId: 'civiclens-d5da2',
    storageBucket: 'civiclens-d5da2.firebasestorage.app',
    iosBundleId: 'com.example.civiclens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtcOOdz50VmuwjRsWJx9XyBYDo-5Y-Z18',
    appId: '1:192377407511:web:a7a7455ed60caade47f452',
    messagingSenderId: '192377407511',
    projectId: 'civiclens-d5da2',
    authDomain: 'civiclens-d5da2.firebaseapp.com',
    storageBucket: 'civiclens-d5da2.firebasestorage.app',
    measurementId: 'G-2N6SHHDSTM',
  );
}
